# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Stimulus

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: oven-sh/setup-bun@v2.0.1
    - run: bun install
    - run: bun run test

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: oven-sh/setup-bun@v2.0.1
    - run: bun install
    - run: bun run lint
